  delete[m
* [32mdevelop[m
  feature[m
  feature-actualitzaradmin[m
  feature-admindoupdates[m
  feature-administracio[m
  feature-adminpanel[m
  feature-adminupdates[m
  feature-contacteAjax[m
  feature-footer[m
  feature-llistaradmin[m
  feature-navbar[m
  feature-navupdate[m
  feature-passwordhash[m
  feature-provesadmin[m
  feature_controladors[m
  feature_vistes[m
  main[m
  mohabranca[m
